# Generated by Django 5.2.4 on 2025-08-03 06:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("results", "0002_alter_useranswer_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProctoringSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("terminated", "Terminated"),
                            ("flagged", "Flagged for Review"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "is_valid",
                    models.BooleanField(
                        default=True, help_text="Mark as invalid if cheating detected"
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                (
                    "webcam_frames",
                    models.JSONField(default=list, help_text="Store webcam frame data"),
                ),
                ("violation_count", models.IntegerField(default=0)),
                (
                    "total_risk_score",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("location_data", models.JSONField(blank=True, default=dict)),
                (
                    "quiz_attempt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proctoring_session",
                        to="results.quizattempt",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proctoring_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="ProctoringSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("enable_webcam", models.BooleanField(default=True)),
                ("face_detection", models.BooleanField(default=True)),
                ("multiple_face_detection", models.BooleanField(default=True)),
                ("prevent_tab_switch", models.BooleanField(default=True)),
                ("prevent_fullscreen_exit", models.BooleanField(default=True)),
                ("prevent_copy_paste", models.BooleanField(default=True)),
                (
                    "risk_threshold",
                    models.DecimalField(decimal_places=2, default=70.0, max_digits=5),
                ),
                ("auto_terminate", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_proctoring_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Proctoring Settings",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Violation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("violation_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "violation_type",
                    models.CharField(
                        choices=[
                            ("multiple_faces", "Multiple Faces Detected"),
                            ("no_face", "No Face Detected"),
                            ("tab_switch", "Tab Switch Detected"),
                            ("fullscreen_exit", "Fullscreen Exit"),
                            ("copy_paste", "Copy/Paste Detected"),
                            ("suspicious_activity", "Suspicious Activity"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "evidence_data",
                    models.JSONField(default=dict, help_text="Store evidence data"),
                ),
                (
                    "risk_score",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True)),
                (
                    "proctoring_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="violations",
                        to="proctoring.proctoringsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
